"""Raw creditor-name alias table.

Data only - the lookup logic that consumes it lives in ``creditor_names``."""

_RAW_CREDITOR_ALIAS_MAP = {
    # 'Salaryfinance' is one word in Aryza, so the substring match against the
    # DB row 'Salary Finance' (two words) misses — alias it explicitly.
    'salaryfinance': 'Salary Finance',
    'salaryfinance loan': 'Salary Finance',
    'salary finance loan': 'Salary Finance',
    'natwest group plc': 'NatWest',
    'natwest plc': 'NatWest',
    'natwest': 'NatWest',
    'rbs': 'NatWest',
    'royal bank of scotland': 'NatWest',
    'natwest current accounts': 'NatWest',
    'lloyds banking group': 'Lloyds Bank',
    'lloyds bank plc': 'Lloyds Bank',
    'lloyds tsb': 'Lloyds Bank',
    'lloyds': 'Lloyds Bank',
    'lloyds bank': 'Lloyds Bank',
    'lloyds bank plc hp': 'Lloyds Bank',
    'mbna': 'MBNA - IVA',
    'mbna limited': 'MBNA - IVA',
    'mbna europe bank': 'MBNA - IVA',
    'barclaycard': 'Barclaycard',
    'barclaycard (including cards below) - iva': 'Barclaycard',
    'barclays bank plc': 'Barclays Bank',
    'barclays': 'Barclays Bank',
    'barclays partner finance': 'Barclays',
    'link financial outsourcing limited': 'Link Financial - IVA',
    'link financial outsourcing': 'Link Financial - IVA',
    'link financial ltd': 'Link Financial - IVA',
    'link financial': 'Link Financial - IVA',
    'link financial limited': 'Link Financial - IVA',
    'asset link': 'Asset Link',
    # JD Williams (its own CreditorCriteria row, restored via
    # Which_Representative_Criteria.md — TIX — see 0021_fix_jd_williams_tix_
    # county_routing.py for provenance). Previously these 3 raw keys all
    # normalised to the SAME "jd williams" key ('jd williams (n brown group)',
    # 'jd williams', 'jd williams (n brown group plc)') and silently collided
    # — only the last one survived, and it pointed at 'Shop Direct' by
    # accident, not design. Consolidated to one entry pointing at the real
    # row. The 3 " ... Company Limited" variants below normalise to distinct
    # keys and were separately broken, pointing at a name that never existed
    # (a typo — "JD WIlliams (N Brown Group)" was never a real row).
    'jd williams': 'JD Williams',
    'jd williams company limited': 'JD Williams',
    'jd williams & company limited': 'JD Williams',
    'jd williams and company limited': 'JD Williams',
    # Shop Direct is a separate, real N Brown Group entity distinct from JD
    # Williams itself — left as its own target.
    'n brown': 'Shop Direct',
    'n brown group': 'Shop Direct',
    'shop direct': 'Shop Direct',
    'shop direct group': 'Shop Direct',
    'the very group limited (wpm)': 'Very',
    'capital one': 'Capital One',
    'capital one bank (europe) plc': 'Capital One',
    '118 118 money': '118 Money',
    '118118 money': '118 Money',
    '118 money': '118 Money',
    'madison cf uk ltd t/a 118 118 money': '118 Money',
    'creation': 'Creation',
    'creation consumer finance': 'Creation',
    'creation consumer finance ltd': 'Creation Consumer Finance',
    'creation financial services': 'Creation',
    'creation finance': 'Creation Financial Services',
    'novuna': 'Hitachi Capital/Credit / Novuna',
    'hitachi capital': 'Hitachi Capital/Credit / Novuna',
    'zopa': 'Zopa - IVA or BKY',
    'zopa bank limited': 'Zopa - IVA or BKY',
    'zopa limited': 'Zopa - IVA or BKY',
    'halifax': 'HBOS - Halifax - IVA',
    'halifax personal loan': 'HBOS - Halifax - IVA',
    'halifax bank': 'HBOS - Halifax - IVA',
    'halifax plc': 'HBOS - Halifax - IVA',
    'bank of scotland': 'HBOS - Bank of Scotland - IVA',
    'bank of scotland credit card': 'HBOS - Bank of Scotland - IVA',
    'bank of scotland plc': 'HBOS - Bank of Scotland - IVA',
    'hsbc': 'HSBC',
    'santander': 'Santander',
    'santander cards': 'Santander Cards',
    'santander consumer finance': 'Santander Consumer Finance',
    'virgin credit card': 'Virgin Credit Card',
    'virgin media': 'Virgin Media',
    'virgin money': 'Virgin Money (Loan) WPM',
    'tesco bank': 'Tesco Bank',
    'tesco mobile': 'Tesco Mobile',
    'american express': 'American Express Service',
    'american express services europe ltd': 'American Express Service',
    'amex': 'American Express Service',
    'vanquis': 'Vanquis Bank',
    'vanquis bank': 'Vanquis Bank',
    'vanquis bank limited': 'Vanquis Bank',
    'aqua': 'Aqua - IVA',
    'newday': 'NewDay',
    'newday limited': 'NewDay',
    'paypal': 'Paypal Europe Ltd',
    'very': 'Very',
    'every day loans': 'Every Day Loans',
    'everyday loans': 'Everyday Loans',
    'next': 'Next Directory',
    'next directory': 'Next Directory',
    'littlewoods': 'Littlewoods',
    'littlewoods.com': 'Littlewoods',
    'studio': 'Studio Cards & Gifts',
    'lowell': 'Lowell',
    'lowell portfolio': 'Lowell',
    'lowell group': 'Lowell',
    'lowell financial': 'Lowell',
    'lowell portfolio i ltd': 'Lowell',
    'pra': 'PRA (Portfolio Recovery Associates) - IVA',
    'portfolio recovery associates': 'PRA (Portfolio Recovery Associates) - IVA',
    'pra group': 'PRA (Portfolio Recovery Associates) - IVA',
    'portfolio recovery': 'PRA (Portfolio Recovery Associates) - IVA',
    'pra group (uk) limited (tix)': 'PRA Group',
    'pra group (uk) ltd c/o wpm': 'PRA Group',
    'pulse': 'Pulse - IVA',
    'lantern': 'Lantern',
    'lantern debt recovery': 'Lantern',
    'lantern debt recovery services ltd': 'Lantern',
    'lantern debt recovery limited - iva or bky': 'Lantern',
    'lantern debt recovery limited - td or das or seq': 'Lantern',
    'perch capital': 'PCO Holdco Sarl - IVA',
    'perch capital limited': 'Perch Capital Limited',
    'cabot': 'Cabot Financial',
    'cabot financial': 'Cabot Financial',
    'cabot financial (europe) ltd': 'Cabot Financial',
    'cabot credit management group limited': 'Cabot Financial',
    'intrum': 'Intrum UK Ltd (previously 1st Credit) - IVA or BKY',
    '1st credit': 'Intrum UK Ltd (previously 1st Credit) - IVA or BKY',
    'arrow global': 'Arrow Global',
    'marlin': 'Marlin Financial - IVA',
    'hoist': 'Hoist Financial',
    'hoist financial': 'Hoist Financial',
    'moorcroft': 'Moorcroft Debt Recovery',
    'moorcroft debt recovery': 'Moorcroft Debt Recovery',
    'jefferson capital': 'Jefferson Capital International Acquisition (JCIA, or their UK operation Creditlink Account Recovery Services CARS)',
    'jcia': 'Jefferson Capital International Acquisition (JCIA, or their UK operation Creditlink Account Recovery Services CARS)',
    'cars': 'Jefferson Capital International Acquisition (JCIA, or their UK operation Creditlink Account Recovery Services CARS)',
    'jc international acquisition': 'Jefferson Capital International Acquisition (JCIA, or their UK operation Creditlink Account Recovery Services CARS)',
    'jc international acquisition llc': 'Jefferson Capital International Acquisition (JCIA, or their UK operation Creditlink Account Recovery Services CARS)',
    'nationwide recovery': 'Nationwide Recovery (SDG) - IVA or TD',
    'max recovery': 'Max Recovery',
    'grove': 'Grove / TTI SPC CarVal (including previous Egg Loans /Britannica Recovery) - IVA',
    'tti spc': 'TTI SPC CarVal / Grove (including previous Egg Loans /Britannica Recovery) - IVA',
    'klarna': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'klarna bank ab': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'klarna uk': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'klarna uk ltd': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'klarna pay later and pay in 3': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'klarna bank ab pay later and pay in 3': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'zilch': 'Zilch',
    'zilch technology limited': 'Zilch',
    # Zable is a trading name of Lendable — not its own CreditorCriteria row.
    # (Previously 'zable' pointed to the unrelated 'NewDay' and was silently
    # shadowed by 'lendable limited t/a zable' pointing to a non-existent
    # 'Zable' row — both normalise to the same key "zable", so only the last
    # one written ever took effect. Fixed to the one real target for both.)
    'zable': 'Lendable',
    'lendable limited t/a zable': 'Lendable',
    'aquis': 'Aquis',
    'fluid': 'Fluid',
    'opus': 'Opus',
    'jaja': 'Jaja Finance Ltd',
    'lendable': 'Lendable',
    'lendable limited t/a autolend': 'Lendable',
    'plata': 'Plata Loans (BAMBOO)',
    'salary finance': 'Salary Finance',
    'ratesetter': 'Ratesetter',
    'funding circle': 'Funding Circle',
    'updraft': 'Updraft',
    'fairscore limited t/a updraft': 'Updraft',
    'tsb': 'TSB Bank',
    'tsb bank': 'TSB Bank',
    'tsb bank plc': 'TSB Bank',
    'nationwide': 'Nationwide Building Society',
    'nationwide building society': 'Nationwide Building Society',
    'first direct': 'First Direct',
    'monzo': 'Monzo Bank',
    'monzo bank': 'Monzo',
    'starling': 'Monzo Bank',
    'argos': 'Argos Card Services',
    'home retail group': 'Argos Card Services',
    'freemans': 'Freemans Catalogue',
    'kaleidoscope': 'Kaleidoscope',
    'look again': 'Look Again',
    'grattan': 'Grattan',
    'octopus energy limited': 'Octopus Energy',
    'british gas consumer': 'British Gas',
    'amigo': 'Amigo',
    'amigo loans': 'Amigo',
    'bamboo': 'Bamboo',
    'bamboo loans': 'Bamboo',
    'bamboo limited (link financial)': 'Bamboo',
    'guarantor my loan': 'Guarantor My Loan',
    'buddy loans': 'Buddy Loans t/a Advancis Ltd',
    'moneybarn': 'Moneybarn',
    'black horse': 'Blackhorse - Blackhorse Finance - IVA',
    'black horse limited': 'Blackhorse - Blackhorse Finance - IVA',
    'black horse - td': 'Blackhorse - Blackhorse Finance - TD',
    'blue motor finance': 'Blue Motor Finance',
    'blue motor finance limited': 'Blue Motor Finance',
    'specialist motor finance': 'Specialist Motor Finance',
    'volkswagen financial services': 'Volkswagen Financial Services',
    'vw financial services': 'Volkswagen Financial Services',
    'fce bank': 'FCE Bank',
    'ford credit': 'FCE Bank',
    'hitachi': 'Hitachi',
    'ikano': 'Ikano Bank AB - IVA or TD or BKY or DAS or SEQ or DRO',
    'granite': 'Granite (Vanquis)',
    'gracombex ltd t/a the money platform': 'The Money Platform',
    # Councils never go through CREDITOR_ALIAS_MAP / CreditorCriteria — they're
    # matched entirely via _match_council_rule() against CouncilRule, which has
    # its own name normalisation and fuzzy fallback. These 3 entries pointed at
    # CreditorCriteria rows that were never meant to exist and were dead code:
    # removed rather than "fixed", since there's nothing here for them to do.
    'west sussex & surrey credit union limited t/a boom community bank': 'Boom Credit Union ALSO known as East Sussex Credit Union Ltd t/a Wave Community Bank:',
    'department for work & pensions (dwp)': 'DWP',
    'hm revenue & customs': 'HM Revenue & Customs',
    # Northridge Finance is Santander Consumer Finance's motor-finance brand,
    # not its own CreditorCriteria row (a migration once added it as a
    # trading_name on that row, but trading_names is reset to [] by every
    # `seed_creditor_criteria` run — pointing the alias straight at the real
    # row is what actually survives).
    'northridge finance ltd': 'Santander Consumer Finance',
    'northridge finance': 'Santander Consumer Finance',
    'castle community bank': 'Castle Community Bank',
    'advanced payment solutions ltd t/a cashplus bank': 'Cashplus',
    'zempler bank limited': 'Cashplus',
    'ccc debt management': 'CCC Debt Management',
    'united trust bank limited': 'United Trust Bank',
    'anderson brookes': 'Anderson Brookes',
    'credit4 limited': 'Credit4',
    'travis perkins plc': 'Travis Perkins',
    'tyrell carpentry contractors limited': 'Tyrell Carpentry',
    'huws gray builders merchant': 'Huws Gray',
    'zopa limited': 'Zopa - IVA or BKY',
    'halifax credit card': 'HBOS - Halifax - IVA',
    'v12 finance': 'V12 Personal Finance',
    'v12 personal finance': 'V12 Personal Finance',
    'admiral financial services ltd': 'Admiral Loans',
    'admiral financial services limited': 'Admiral Loans',
    'shop direct finance company ltd': 'Shop Direct Finance Company - IVA or TD',
    'home retail group card services': 'Home Retail Group',
    'hbos - halifax - iva': 'HBOS - Halifax - IVA',
    'secure trust bank plc': 'Secure Trust Bank',
    'mbna ltd': 'MBNA - IVA',
    'jd williams ta jacamo': 'Shop Direct',

    # Found via a sweep of real Aryza creditor names that were silently failing
    # to match any CreditorCriteria row (verified against the DB, not guessed —
    # see conversation re: case 394638 WATCH detection investigation).
    'jaja finance': 'Jaja Finance Ltd',
    'marks and spencer': 'Marks & Spencer',
    "sainsbury's bank": 'Sainsburys Bank',
    'sainsbury bank': 'Sainsburys Bank',
    'vanquis loans': 'Vanquis Bank',
    'co-operative bank': 'The Co-operative Bank',
    'the cooperative': 'The Co-operative Bank',
    'grattans': 'Grattan',
    'bank of ireland': 'AA Bank of Ireland',
    'monozo bank': 'Monzo Bank',  # typo seen in live data
    'bank of scotland personal loan': 'HBOS - Bank of Scotland - IVA',
    # PayPal's legal-entity name has "(Europe)" in the MIDDLE of the string, so
    # normalise_creditor_name's end-anchored parenthetical strip never reaches
    # it — explicit aliases needed for the real Aryza/credit-report renderings.
    'paypal': 'Paypal Europe Ltd',
    'paypal (europe) sarl et cie sca': 'Paypal Europe Ltd',
    'paypal (europe) sarl & cia, sca': 'Paypal Europe Ltd',
    'paypal credit': 'Paypal Europe Ltd',
    'redcats catalogue': 'Redcats UK',
}
