# Generated by Django 6.0.4 on 2026-05-14 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0006_seed_banking_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditorcriteria',
            options={'verbose_name_plural': 'Creditor Criteria'},
        ),
        migrations.AlterModelOptions(
            name='globalcriteria',
            options={'verbose_name_plural': 'Global Criteria'},
        ),
        migrations.RemoveIndex(
            model_name='creditorcriteria',
            name='debt_app_creditorcriteria_name_idx',
        ),
        migrations.RenameIndex(
            model_name='creditorcriteria',
            new_name='debt_app_cr_represe_126b4f_idx',
            old_name='debt_app_creditorcriteria_representative_idx',
        ),
        migrations.RenameIndex(
            model_name='creditorcriteria',
            new_name='debt_app_cr_is_acti_efd456_idx',
            old_name='debt_app_creditorcriteria_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='criteriadecision',
            new_name='debt_app_cr_applica_3009af_idx',
            old_name='debt_app_criteriadecision_application_id_idx',
        ),
        migrations.RenameIndex(
            model_name='criteriadecision',
            new_name='debt_app_cr_trigger_07ea8e_idx',
            old_name='debt_app_criteriadecision_triggered_at_idx',
        ),
        migrations.RenameIndex(
            model_name='globalcriteria',
            new_name='debt_app_gl_rule_ke_bfbbd1_idx',
            old_name='debt_app_globalcriteria_rule_key_idx',
        ),
        migrations.RenameIndex(
            model_name='globalcriteria',
            new_name='debt_app_gl_criteri_4a4df6_idx',
            old_name='debt_app_globalcriteria_criteria_set_idx',
        ),
        migrations.AlterField(
            model_name='creditorcriteria',
            name='parent_group',
            field=models.CharField(blank=True, help_text="Banking group e.g. 'Lloyds Banking Group'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalcriteria',
            name='rule_key',
            field=models.CharField(help_text="Unique identifier for the rule (e.g., 'min_debt', 'watch_single_creditor')", max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='creditorcriteria',
            index=models.Index(fields=['creditor_name'], name='debt_app_cr_credito_1baa3a_idx'),
        ),
    ]
