# Generated by Django 6.0.4 on 2026-05-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0033_buddy_loans_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilrule',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='councilrule',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='councilrule',
            name='criteria_changed_from_rej_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
