# Generated by Django 6.0.4 on 2026-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0035_globalcriteria_add_documentation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globalcriteria',
            new_name='debt_app_gl_categor_f038cb_idx',
            old_name='debt_app_globalcriteria_category_idx',
        ),
        migrations.RenameIndex(
            model_name='globalcriteria',
            new_name='debt_app_gl_is_acti_ca81e8_idx',
            old_name='debt_app_globalcriteria_is_active_idx',
        ),
        migrations.AddField(
            model_name='creditorcriteria',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditorcriteria',
            name='criteria_notes',
            field=models.TextField(blank=True, help_text='General criteria notes for this creditor', null=True),
        ),
        migrations.AddField(
            model_name='creditorcriteria',
            name='raw_updated_criteria',
            field=models.CharField(blank=True, help_text="Raw text from the 'updated criteria' column", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalcriteria',
            name='related_rules',
            field=models.JSONField(blank=True, default=list, help_text="List of related rule keys (e.g., ['TIG-01', 'TIG-02'])", null=True),
        ),
    ]
