# Generated by Django 6.0.4 on 2026-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0036_rename_debt_app_globalcriteria_category_idx_debt_app_gl_categor_f038cb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorcriteria',
            name='source_sheet',
            field=models.CharField(blank=True, help_text='The Excel sheet this creditor was primarily sourced from', max_length=100, null=True),
        ),
    ]
