# Generated by Django 6.0.2 on 2026-05-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0038_criteriadecision_result_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorResolutionMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=500)),
                ('normalised_name', models.CharField(blank=True, max_length=500)),
                ('case_reference', models.CharField(max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=300)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['raw_name'], name='debt_app_cr_raw_nam_95b194_idx'), models.Index(fields=['resolved', 'logged_at'], name='debt_app_cr_resolve_b6526d_idx')],
            },
        ),
    ]
