# Generated by Django 6.0.2 on 2026-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0039_creditorresolutionmiss'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcriteria',
            name='action',
            field=models.TextField(blank=True, help_text='Recommended action if this rule is triggered', null=True),
        ),
    ]
