# Generated by Django 6.0.2 on 2026-05-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0040_globalcriteria_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriadecision',
            name='recommended_solution',
            field=models.CharField(choices=[('IVA', 'IVA - Individual Voluntary Arrangement'), ('IVA NOT SUITABLE', 'IVA Not Suitable'), ('IVA POSSIBLE', 'IVA Possible - Review Flagged Items'), ('DMP', 'DMP - Debt Management Plan'), ('BREATHING_SPACE', 'Debt Respite Scheme (Breathing Space)'), ('FREE_SECTOR', 'Free Sector Solution'), ('UNCLEAR', 'Unclear')], max_length=20),
        ),
    ]
