# Generated by Django 6.0.2 on 2026-05-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0041_add_breathing_space_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('upper_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guideline_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureGuideline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('max', models.BooleanField(default=False)),
                ('min', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('adult_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_1_child_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_1_child_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_1_child_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_1_child_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_1_child_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_2_child_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_2_child_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_2_child_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_2_child_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_2_child_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_vehicle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_adult', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_adult', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_under_16', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_16_18', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('watch_per_adult', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_watch_per_adult', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('watch_per_vehicle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_watch_per_vehicle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('one_adult_cap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('two_adults_cap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('formula', models.TextField(blank=True)),
                ('below_action', models.CharField(blank=True, max_length=50)),
                ('above_action', models.CharField(blank=True, max_length=50)),
                ('mismatch_action', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidelines', to='debt_app.guidelinecategory')),
            ],
            options={
                'db_table': 'expenditure_guidelines',
                'ordering': ['category_group__sort_order', 'sort_order', 'category'],
            },
        ),
    ]
