# Generated by Django 6.0.2 on 2026-05-25 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0042_sfs_expenditure_guidelines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorcriteria',
            name='requires_credit_report',
            field=models.BooleanField(default=False, help_text='If True, engine emits FLAG when no credit report is uploaded'),
        ),
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aryza_reference', models.CharField(db_index=True, help_text='Aryza case reference this report belongs to', max_length=255)),
                ('uploaded_file', models.FileField(help_text='Raw PDF file', upload_to='credit_reports/%Y/%m/')),
                ('agency', models.CharField(blank=True, default='', help_text='Detected credit agency: Experian, Equifax, TransUnion, Unknown', max_length=100)),
                ('client_name_on_report', models.CharField(blank=True, default='', help_text='Client name as it appears on the credit report', max_length=255)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, help_text='Structured per-creditor data extracted from PDF', null=True)),
                ('extraction_error', models.TextField(blank=True, default='', help_text='Error message if extraction failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_credit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['aryza_reference'], name='debt_app_cr_aryza_r_d3eef1_idx')],
            },
        ),
    ]
