# Generated by Django 6.0.2 on 2026-06-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0046_department_sfs_and_feature_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('general_creditors', 'General Creditors'), ('representative_creditors', 'Representative Creditors'), ('global_rules', 'Global Rules'), ('councils', 'Councils'), ('dividends', 'Dividends'), ('sfs_guidelines', 'SFS Guidelines')], help_text='Feature to which this permission applies', max_length=50)),
                ('permission_level', models.CharField(choices=[('READ', 'Read Only'), ('WRITE', 'Read & Write')], default='READ', help_text='READ: View-only, WRITE: Full access (edit, delete, add)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Feature Permission',
                'verbose_name_plural': 'Department Feature Permissions',
                'ordering': ['department', 'feature_key'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='departmentcouncilvisibility',
            name='unique_dept_council_visibility',
        ),
        migrations.RemoveConstraint(
            model_name='departmentcreditorvisibility',
            name='unique_dept_creditor_visibility',
        ),
        migrations.RemoveConstraint(
            model_name='departmentrulevisibility',
            name='unique_dept_rule_visibility',
        ),
        migrations.AlterUniqueTogether(
            name='departmentcouncilvisibility',
            unique_together={('department', 'council')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentcreditorvisibility',
            unique_together={('department', 'creditor')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentrulevisibility',
            unique_together={('department', 'rule_key')},
        ),
        migrations.AddField(
            model_name='departmentfeaturepermission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='debt_app.department'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentfeaturepermission',
            unique_together={('department', 'feature_key')},
        ),
    ]
