# Generated by Django 6.0.2 on 2026-06-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0051_phase0_data_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorcriteria',
            name='reject_if_aoe',
            field=models.BooleanField(default=False, help_text='Reject if an Attachment of Earnings order is already in place'),
        ),
        migrations.AddField(
            model_name='creditorcriteria',
            name='reject_if_ccj',
            field=models.BooleanField(default=False, help_text='Reject if the client has a County Court Judgment on their credit report'),
        ),
    ]
