# Generated by Django 6.0.2 on 2026-06-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0056_retire_tig14_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorcriteria',
            name='reject_if_recent_spend_months',
            field=models.IntegerField(blank=True, help_text='Reject if client has had any transactions matching this creditor name in the last N months. Checked against gold_transactions in the case payload.', null=True),
        ),
    ]
