# Generated by Django 6.0.6 on 2026-07-06 09:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_county_councils(apps, schema_editor):
    """
    CountyCouncilRouting.county_name has always held the county's name as a
    repeated string (once per district row) with no parent record. Create one
    CountyCouncil per distinct county_name already present and point every
    routing row at it, so the new criteria fields have somewhere to live.
    """
    CountyCouncil = apps.get_model('debt_app', 'CountyCouncil')
    CountyCouncilRouting = apps.get_model('debt_app', 'CountyCouncilRouting')

    names = CountyCouncilRouting.objects.values_list('county_name', flat=True).distinct()
    for name in names:
        county, _ = CountyCouncil.objects.get_or_create(county_name=name)
        CountyCouncilRouting.objects.filter(county_name=name).update(county=county)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0058_creditor_outcome_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('WILL_CONSIDER', 'Will Consider'), ('DO_NOT_VOTE', 'Do Not Vote'), ('CONDITIONAL_VOTER', 'Conditional Voter')], default='WILL_CONSIDER', max_length=20)),
                ('deals_with_council_tax', models.BooleanField(default=False, help_text='Most county councils delegate council tax collection to their districts.')),
                ('min_dividend_pence', models.IntegerField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'County Council',
                'verbose_name_plural': 'County Councils',
                'ordering': ['county_name'],
            },
        ),
        migrations.AddField(
            model_name='countycouncilrouting',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='debt_app.countycouncil'),
        ),
        migrations.RunPython(backfill_county_councils, noop_reverse),
    ]
