# Generated by Django 6.0.6 on 2026-07-06 10:02

from django.db import migrations, models


def flip_generic_will_consider_to_no_criteria(apps, schema_editor):
    """
    Every CountyCouncil row that was seeded WITHOUT explicit accept/reject
    criteria in the ground-truth md defaulted to WILL_CONSIDER, which
    falsely implies the county votes on cases. Almost all of them explicitly
    state they don't handle council tax and delegate to districts — flip
    those generic defaults to NO_CRITERIA. Rows with real criteria (e.g.
    Buckinghamshire, status=CONDITIONAL_VOTER) are untouched.
    """
    CountyCouncil = apps.get_model('debt_app', 'CountyCouncil')
    CountyCouncil.objects.filter(status='WILL_CONSIDER').update(status='NO_CRITERIA')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0059_add_county_council_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countycouncil',
            name='status',
            field=models.CharField(choices=[('NO_CRITERIA', 'No Direct Criteria — delegates to districts'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('WILL_CONSIDER', 'Will Consider'), ('DO_NOT_VOTE', 'Do Not Vote'), ('CONDITIONAL_VOTER', 'Conditional Voter')], default='NO_CRITERIA', max_length=20),
        ),
        migrations.RunPython(flip_generic_will_consider_to_no_criteria, noop_reverse),
    ]
