# Generated by Django on 2026-07-08
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0060_county_council_no_criteria_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorVoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(blank=True, null=True)),
                ('accepted_count', models.IntegerField(blank=True, null=True)),
                ('latest_vote_date', models.DateField(blank=True, null=True)),
                ('latest_vote_outcome', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified')], max_length=20, null=True)),
                ('crm_rows_covered', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('creditor_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_summaries', to='debt_app.creditorcriteria')),
                ('council_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_summaries', to='debt_app.councilrule')),
                ('county_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_summaries', to='debt_app.countycouncil')),
            ],
            options={
                'verbose_name_plural': 'Creditor Vote Summaries',
            },
        ),
        migrations.AddConstraint(
            model_name='creditorvotesummary',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(creditor_criteria__isnull=False) & models.Q(council_rule__isnull=True) & models.Q(county_council__isnull=True)) |
                    (models.Q(creditor_criteria__isnull=True) & models.Q(council_rule__isnull=False) & models.Q(county_council__isnull=True)) |
                    (models.Q(creditor_criteria__isnull=True) & models.Q(council_rule__isnull=True) & models.Q(county_council__isnull=False))
                ),
                name='exactly_one_creditor_type_set',
            ),
        ),
    ]
