# Generated by Django 6.0.7 on 2026-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0061_add_creditor_vote_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditorvotesummary',
            name='latest_vote_outcome',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('pod', 'POD')], max_length=20, null=True),
        ),
    ]
