# Generated by Django 6.0.7 on 2026-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0062_alter_creditorvotesummary_latest_vote_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorvotesummary',
            name='modified_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditorvotesummary',
            name='pod_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
