# Generated by Django 6.0.2 on 2026-07-09 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0063_creditorvotesummary_modified_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('stage', models.CharField(blank=True, default='', max_length=100)),
                ('trigger_source', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled/Cron'), ('CLI', 'CLI')], default='CLI', max_length=10)),
                ('dry_run', models.BooleanField(default=False)),
                ('crm_rows_fetched', models.IntegerField(blank=True, null=True)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('creditor_criteria_count', models.IntegerField(default=0)),
                ('council_rule_count', models.IntegerField(default=0)),
                ('county_council_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
