# Generated by Django 6.0.7 on 2026-07-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0064_crmsyncrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorVoteChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('pod', 'POD')], max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt_app.crmsyncrun')),
                ('vote_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt_app.creditorvotesummary')),
            ],
        ),
    ]
