# Generated by Django 6.0.7 on 2026-07-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0065_creditorvotechangeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorMocAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField()),
                ('triggered_by_status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('pod', 'POD')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt_app.creditorvotesummary')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vote_summary', 'alert_date'), name='unique_moc_alert_per_creditor_per_day')],
            },
        ),
    ]
