# Generated by Django 6.0.7 on 2026-07-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0066_creditormocalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorNonAcceptMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_date', models.DateField()),
                ('first_event_at', models.DateTimeField()),
                ('third_event_at', models.DateTimeField()),
                ('status_breakdown', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt_app.creditorvotesummary')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vote_summary', 'milestone_date'), name='uniq_nonaccept_milestone_per_day')],
            },
        ),
    ]
