# Generated by Django 6.0.2 on 2026-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0069_moc_alert_emailed_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MocDigestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.TextField(blank=True, default='')),
                ('alerts_count', models.IntegerField(default=0)),
                ('milestones_count', models.IntegerField(default=0)),
                ('vote_changes_total', models.IntegerField(default=0)),
            ],
        ),
    ]
