# Generated by Django 6.0.2 on 2026-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0070_mocdigestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source_department',
            field=models.CharField(blank=True, help_text='Name of the department the user belonged to at the moment the first assessment was run for this case. A permanent snapshot — set once, never overwritten by later runs, and unaffected by later renames/deletion of the Department record itself.', max_length=100, null=True),
        ),
    ]
