# Generated by Django 6.0.4 on 2026-08-29 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0075_reparent_group_caps_into_natural_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditreport',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('extracted_empty', 'Extracted — No Accounts Found'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='criteriadecision',
            name='recommended_solution',
            field=models.CharField(choices=[('IVA', 'IVA - Individual Voluntary Arrangement'), ('IVA NOT SUITABLE', 'IVA Not Suitable'), ('IVA POSSIBLE', 'IVA Possible - Review Flagged Items'), ('DMP', 'DMP - Debt Management Plan'), ('DRO', 'DRO - Debt Relief Order'), ('BREATHING_SPACE', 'Debt Respite Scheme (Breathing Space)'), ('FREE_SECTOR', 'Free Sector Solution'), ('UNCLEAR', 'Unclear')], max_length=20),
        ),
        migrations.CreateModel(
            name='CouncilTaxEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aryza_reference', models.CharField(db_index=True, help_text='Aryza case reference this evidence belongs to', max_length=255)),
                ('uploaded_file', models.FileField(help_text='Raw image or PDF file', upload_to='council_tax_evidence/%Y/%m/')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('extracted_empty', 'Extracted — No Accounts Found'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('balance_pence', models.IntegerField(blank=True, null=True)),
                ('council_name', models.CharField(blank=True, default='', max_length=255)),
                ('liability_order_court', models.CharField(blank=True, default='', max_length=255)),
                ('liability_order_date', models.DateField(blank=True, null=True)),
                ('client_salutation_name', models.CharField(blank=True, default='', max_length=255)),
                ('extraction_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_council_tax_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['aryza_reference'], name='debt_app_co_aryza_r_eb4abd_idx')],
            },
        ),
    ]
