# Generated by Django 6.0.2 on 2026-09-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0076_alter_creditreport_extraction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditreport',
            name='client_address_on_report',
            field=models.CharField(blank=True, default='', help_text="Client's own address as it appears on the credit report, cleaned (whitespace/comma/postcode normalised) by integrations.credit_report._clean_address. This is the applicant's address, not any creditor's — no supported report format carries a creditor's own postal address.", max_length=500),
        ),
    ]
