# Generated by Django 6.0.4 on 2026-10-05 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0077_creditreport_client_address_on_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentfeatureaccess',
            name='feature_key',
            field=models.CharField(choices=[('general_creditors', 'General Creditors'), ('representative_creditors', 'Representative Creditors'), ('global_rules', 'Global Rules'), ('councils', 'Councils'), ('dividends', 'Dividends'), ('sfs_guidelines', 'SFS Guidelines'), ('run_assessment', 'Run Assessment'), ('decisions', 'Decisions'), ('evidence', 'Evidence'), ('user_management', 'User Management'), ('lead_gen_check', 'Lead Gen Check'), ('lead_gen_reporting', 'Lead Gen Reporting'), ('criteria_changes', 'Criteria Changes (propose / trial)'), ('criteria_approval', 'Criteria Approval (sign-off / go live)')], max_length=50),
        ),
        migrations.CreateModel(
            name='CriteriaChangeRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField(help_text='Why the change is needed (required).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TRIALLED', 'Trialled — awaiting sign-off'), ('LIVE', 'Approved and live'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('items', models.JSONField(help_text='[{"model", "object_id", "object_label", "field", "old_value", "new_value"}]')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_rollback', models.BooleanField(default=False)),
                ('trial_run_at', models.DateTimeField(blank=True, null=True)),
                ('trial_live_fingerprint', models.CharField(blank=True, default='', help_text='Live criteria fingerprint the trial ran against; sign-off requires it to be unchanged.', max_length=64)),
                ('trial_summary', models.JSONField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria_changes_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='Second manager who approved or rejected the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trial_run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriteriaVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot', models.JSONField(help_text='Managed criteria fields for every managed row.')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('code_version', models.CharField(blank=True, default='', max_length=64)),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='debt_app.criteriachangerequest')),
                ('created_by', models.ForeignKey(blank=True, help_text='The approver who made this version live (None for the automatic baseline).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='criteriachangerequest',
            name='applied_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='debt_app.criteriaversion'),
        ),
        migrations.AddField(
            model_name='criteriachangerequest',
            name='rollback_to_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='debt_app.criteriaversion'),
        ),
        migrations.CreateModel(
            name='CriteriaChangeAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('object_label', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.JSONField(null=True)),
                ('new_value', models.JSONField(null=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_version', models.CharField(blank=True, default='', max_length=64)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='debt_app.criteriachangerequest')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='debt_app.criteriaversion')),
            ],
            options={
                'ordering': ['-applied_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadGenCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text="Snapshot of the user's username at check time.", max_length=150)),
                ('department_name', models.CharField(blank=True, default='', help_text="Snapshot of the user's department at check time.", max_length=100)),
                ('aryza_reference', models.CharField(db_index=True, max_length=255)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OK', 'Checked'), ('CASE_NOT_FOUND', 'Case not found'), ('ARYZA_TIMEOUT', 'Aryza timed out'), ('ARYZA_UNAVAILABLE', 'Aryza unavailable'), ('ARYZA_DATA_ERROR', 'Aryza data error'), ('CREDIT_REPORT_INVALID', 'Credit report file rejected'), ('CREDIT_REPORT_FAILED', 'Credit report could not be read'), ('ENGINE_ERROR', 'Assessment error')], max_length=30)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('iva_outcome', models.CharField(blank=True, choices=[('POTENTIALLY_SUITABLE', 'IVA potentially suitable'), ('NEEDS_REVIEW', 'IVA potentially suitable, needs review'), ('NOT_SUITABLE', 'IVA not currently suitable')], default='', max_length=30)),
                ('dmp_outcome', models.CharField(blank=True, choices=[('POTENTIALLY_SUITABLE', 'DMP potentially suitable'), ('NOT_SUITABLE', 'DMP not currently suitable'), ('NOT_ASSESSED', 'DMP not assessed')], default='', max_length=30)),
                ('dro_referral', models.BooleanField(default=False)),
                ('overall_outcome', models.CharField(blank=True, choices=[('POTENTIALLY_SUITABLE', 'Potentially suitable'), ('DRO_REFER', 'DRO potentially suitable / refer for review'), ('DOES_NOT_MEET_CRITERIA', 'Does not currently meet criteria')], default='', max_length=30)),
                ('engine_recommended_solution', models.CharField(blank=True, default='', help_text="assess_case()'s own solution code for this run (e.g. IVA_VIABLE, FORCED_DRO_LG).", max_length=50)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('evidence_required', models.JSONField(blank=True, default=list)),
                ('credit_report_id', models.IntegerField(blank=True, help_text='CreditReport used (or uploaded) for this check. Plain id — reports are never cascaded.', null=True)),
                ('credit_report_status', models.CharField(blank=True, default='', max_length=30)),
                ('criteria_version', models.CharField(blank=True, default='', max_length=50)),
                ('criteria_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 of the engine-relevant criteria configuration at check time.', max_length=64)),
                ('code_version', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_gen_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['user', 'checked_at'], name='debt_app_le_user_id_5d8ba6_idx')],
            },
        ),
    ]
