from django.urls import path
from debt_app.views.criteria_views import (
    AssessCaseView,
    AssessHistoryView,
    AssessHistoryDetailView,
    CreditorListView,
    CreditorDetailView,
    RulesListView,
    RulesDetailView,
    RuleHistoryView,
    CouncilRuleListView,
    CouncilRuleDetailView,
    ApplicationListView,
    ApplicationDetailView,
    EvidenceLedgerListView,
    EvidenceLedgerDetailView,
    VoterListView,
    VoterDetailView,
    UserListView,
    UserDetailView,
)
from debt_app.views.evaluate_view import EvaluateCaseView
from debt_app.views.evaluation_history_view import EvaluationHistoryView

urlpatterns = [
    path("assess/",                         AssessCaseView.as_view()),
    path('cases/<str:case_id>/evaluate', EvaluateCaseView.as_view(), name='evaluate-case'),
    path('cases/<str:case_id>/evaluations', EvaluationHistoryView.as_view(), name='evaluation-history'),
    path("assess/history/",                 AssessHistoryView.as_view()),
    path("assess/history/<uuid:id>/",       AssessHistoryDetailView.as_view()),
    path("creditors/",                      CreditorListView.as_view()),
    path("creditors/<int:id>/",             CreditorDetailView.as_view()),
    path("rules/",                          RulesListView.as_view()),
    path("rules/<str:rule_key>/",           RulesDetailView.as_view()),
    path("rules/<str:rule_key>/history/", RuleHistoryView.as_view()),
    path("councils/",                       CouncilRuleListView.as_view()),
    path("councils/<int:pk>/",              CouncilRuleDetailView.as_view()),
    path("applications/",                   ApplicationListView.as_view()),
    path("applications/<int:pk>/",          ApplicationDetailView.as_view()),
    path("evidence/",                       EvidenceLedgerListView.as_view()),
    path("evidence/<int:pk>/",              EvidenceLedgerDetailView.as_view()),
    path("voters/",                         VoterListView.as_view()),
    path("voters/<int:pk>/",               VoterDetailView.as_view()),
    path("users/",                          UserListView.as_view()),
    path("users/<int:pk>/",                UserDetailView.as_view()),
]
